# Activity 1

### Aggregate the data into one Data Frame using Pandas

Pay attention that files may have different names for the same column. therefore, make sure that you unify the columns names before concating them.

In [1]:
import pandas as pd
import numpy as np
df1 = pd.read_csv("file1.csv")
df1.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [2]:
df2 = pd.read_csv("file2.csv")
df2.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Total Claim Amount', 'Policy Type', 'Vehicle Class'],
      dtype='object')

In [3]:
df3 = pd.read_csv("file3.csv")
df3.columns

Index(['Customer', 'State', 'Customer Lifetime Value', 'Education', 'Gender',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Total Claim Amount', 'Vehicle Class'],
      dtype='object')

### Rename ST, GENDER in File 3 in order to concatenate everything to File 4

In [4]:
df3 = df3.rename(columns={"State":"ST","Gender":"GENDER"})

In [5]:
file4 = pd.concat([df1,df2,df3], axis=0)

In [6]:
# (PZ) here i would use a different name from file4. maybe df would be more appropriate because it's the
# main dataframe and not a file

In [7]:
file4

Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master   
1     QZ44356     Arizona      F              Bachelor   
2     AI49188      Nevada      F              Bachelor   
3     WW63253  California      M              Bachelor   
4     GA49547  Washington      M  High School or Below   
...       ...         ...    ...                   ...   
7065  LA72316  California      M              Bachelor   
7066  PK87824  California      F               College   
7067  TD14365  California      M              Bachelor   
7068  UP19263  California      M               College   
7069  Y167826  California      M               College   

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0   
1                 697953.59%      0.0                  94.0   
2                1288743.17%  48767.0                 108.0   
3                 764586.18%      0.0                 106.0   
4                 536307.65%  36357.0                  68.0   
...                      ...      ...                   ...   
7065             23405.98798  71941.0                  73.0   
7066             3096.511217  21604.0                  79.0   
7067             8163.890428      0.0                  85.0   
7068             7524.442436  21941.0                  96.0   
7069             2611.836866      0.0                  77.0   

     Number of Open Complaints     Policy Type  Vehicle Class  \
0                       1/0/00   Personal Auto  Four-Door Car   
1                       1/0/00   Personal Auto  Four-Door Car   
2                       1/0/00   Personal Auto   Two-Door Car   
3                       1/0/00  Corporate Auto            SUV   
4                       1/0/00   Personal Auto  Four-Door Car   
...                        ...             ...            ...   
7065                         0   Personal Auto  Four-Door Car   
7066                         0  Corporate Auto  Four-Door Car   
7067                         3  Corporate Auto  Four-Door Car   
7068                         0   Personal Auto  Four-Door Car   
7069                         0  Corporate Auto   Two-Door Car   

      Total Claim Amount  
0               2.704934  
1            1131.464935  
2             566.472247  
3             529.881344  
4              17.269323  
...                  ...  
7065          198.234764  
7066          379.200000  
7067          790.784983  
7068          691.200000  
7069          369.600000  

[12074 rows x 11 columns]

In [8]:
file4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12074 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Customer                   9137 non-null   object 
 1   ST                         9137 non-null   object 
 2   GENDER                     9015 non-null   object 
 3   Education                  9137 non-null   object 
 4   Customer Lifetime Value    9130 non-null   object 
 5   Income                     9137 non-null   float64
 6   Monthly Premium Auto       9137 non-null   float64
 7   Number of Open Complaints  9137 non-null   object 
 8   Policy Type                9137 non-null   object 
 9   Vehicle Class              9137 non-null   object 
 10  Total Claim Amount         9137 non-null   float64
dtypes: float64(3), object(8)
memory usage: 1.1+ MB


In [9]:
file4.rename(columns={"ST":"State","GENDER":"Gender"},inplace=True)

In [10]:
file4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12074 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Customer                   9137 non-null   object 
 1   State                      9137 non-null   object 
 2   Gender                     9015 non-null   object 
 3   Education                  9137 non-null   object 
 4   Customer Lifetime Value    9130 non-null   object 
 5   Income                     9137 non-null   float64
 6   Monthly Premium Auto       9137 non-null   float64
 7   Number of Open Complaints  9137 non-null   object 
 8   Policy Type                9137 non-null   object 
 9   Vehicle Class              9137 non-null   object 
 10  Total Claim Amount         9137 non-null   float64
dtypes: float64(3), object(8)
memory usage: 1.1+ MB


### Standardizing header names

In [11]:
def standardizing_header_names(file4):
    """makes everything lower case"""
    file4.columns=[i.lower() for i in file4.columns]
    return file4

In [12]:
standardizing_header_names(file4)

customer       state gender             education  \
0     RB50392  Washington    NaN                Master   
1     QZ44356     Arizona      F              Bachelor   
2     AI49188      Nevada      F              Bachelor   
3     WW63253  California      M              Bachelor   
4     GA49547  Washington      M  High School or Below   
...       ...         ...    ...                   ...   
7065  LA72316  California      M              Bachelor   
7066  PK87824  California      F               College   
7067  TD14365  California      M              Bachelor   
7068  UP19263  California      M               College   
7069  Y167826  California      M               College   

     customer lifetime value   income  monthly premium auto  \
0                        NaN      0.0                1000.0   
1                 697953.59%      0.0                  94.0   
2                1288743.17%  48767.0                 108.0   
3                 764586.18%      0.0                 106.0   
4                 536307.65%  36357.0                  68.0   
...                      ...      ...                   ...   
7065             23405.98798  71941.0                  73.0   
7066             3096.511217  21604.0                  79.0   
7067             8163.890428      0.0                  85.0   
7068             7524.442436  21941.0                  96.0   
7069             2611.836866      0.0                  77.0   

     number of open complaints     policy type  vehicle class  \
0                       1/0/00   Personal Auto  Four-Door Car   
1                       1/0/00   Personal Auto  Four-Door Car   
2                       1/0/00   Personal Auto   Two-Door Car   
3                       1/0/00  Corporate Auto            SUV   
4                       1/0/00   Personal Auto  Four-Door Car   
...                        ...             ...            ...   
7065                         0   Personal Auto  Four-Door Car   
7066                         0  Corporate Auto  Four-Door Car   
7067                         3  Corporate Auto  Four-Door Car   
7068                         0   Personal Auto  Four-Door Car   
7069                         0  Corporate Auto   Two-Door Car   

      total claim amount  
0               2.704934  
1            1131.464935  
2             566.472247  
3             529.881344  
4              17.269323  
...                  ...  
7065          198.234764  
7066          379.200000  
7067          790.784983  
7068          691.200000  
7069          369.600000  

[12074 rows x 11 columns]

### Removing duplicates

In [13]:
file4 = file4.drop_duplicates()

In [14]:
file4

customer       state gender             education  \
0     RB50392  Washington    NaN                Master   
1     QZ44356     Arizona      F              Bachelor   
2     AI49188      Nevada      F              Bachelor   
3     WW63253  California      M              Bachelor   
4     GA49547  Washington      M  High School or Below   
...       ...         ...    ...                   ...   
7065  LA72316  California      M              Bachelor   
7066  PK87824  California      F               College   
7067  TD14365  California      M              Bachelor   
7068  UP19263  California      M               College   
7069  Y167826  California      M               College   

     customer lifetime value   income  monthly premium auto  \
0                        NaN      0.0                1000.0   
1                 697953.59%      0.0                  94.0   
2                1288743.17%  48767.0                 108.0   
3                 764586.18%      0.0                 106.0   
4                 536307.65%  36357.0                  68.0   
...                      ...      ...                   ...   
7065             23405.98798  71941.0                  73.0   
7066             3096.511217  21604.0                  79.0   
7067             8163.890428      0.0                  85.0   
7068             7524.442436  21941.0                  96.0   
7069             2611.836866      0.0                  77.0   

     number of open complaints     policy type  vehicle class  \
0                       1/0/00   Personal Auto  Four-Door Car   
1                       1/0/00   Personal Auto  Four-Door Car   
2                       1/0/00   Personal Auto   Two-Door Car   
3                       1/0/00  Corporate Auto            SUV   
4                       1/0/00   Personal Auto  Four-Door Car   
...                        ...             ...            ...   
7065                         0   Personal Auto  Four-Door Car   
7066                         0  Corporate Auto  Four-Door Car   
7067                         3  Corporate Auto  Four-Door Car   
7068                         0   Personal Auto  Four-Door Car   
7069                         0  Corporate Auto   Two-Door Car   

      total claim amount  
0               2.704934  
1            1131.464935  
2             566.472247  
3             529.881344  
4              17.269323  
...                  ...  
7065          198.234764  
7066          379.200000  
7067          790.784983  
7068          691.200000  
7069          369.600000  

[9135 rows x 11 columns]

### Dropping column customer as it is only a unique identifier for each row of data

In [15]:
def drop_column(file4) :
    file4.drop(columns=["customer"], inplace=True)
    return file4

In [16]:
file4.drop(columns='customer', inplace=True)

/var/folders/lj/my6r3k650wl54v5nz5r6x5cm0000gn/T/ipykernel_41054/3625064585.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file4.drop(columns='customer', inplace=True)


### Rearranging columns

In [17]:
# (PZ)  is it necessary to rearrange columns in order to merge?

In [18]:
list(file4.columns)

['state',
 'gender',
 'education',
 'customer lifetime value',
 'income',
 'monthly premium auto',
 'number of open complaints',
 'policy type',
 'vehicle class',
 'total claim amount']

In [19]:
file4 = file4[['gender','state','education','income','customer lifetime value','policy type','vehicle class','monthly premium auto','total claim amount','number of open complaints']]

In [20]:
file4

gender       state             education   income  \
0       NaN  Washington                Master      0.0   
1         F     Arizona              Bachelor      0.0   
2         F      Nevada              Bachelor  48767.0   
3         M  California              Bachelor      0.0   
4         M  Washington  High School or Below  36357.0   
...     ...         ...                   ...      ...   
7065      M  California              Bachelor  71941.0   
7066      F  California               College  21604.0   
7067      M  California              Bachelor      0.0   
7068      M  California               College  21941.0   
7069      M  California               College      0.0   

     customer lifetime value     policy type  vehicle class  \
0                        NaN   Personal Auto  Four-Door Car   
1                 697953.59%   Personal Auto  Four-Door Car   
2                1288743.17%   Personal Auto   Two-Door Car   
3                 764586.18%  Corporate Auto            SUV   
4                 536307.65%   Personal Auto  Four-Door Car   
...                      ...             ...            ...   
7065             23405.98798   Personal Auto  Four-Door Car   
7066             3096.511217  Corporate Auto  Four-Door Car   
7067             8163.890428  Corporate Auto  Four-Door Car   
7068             7524.442436   Personal Auto  Four-Door Car   
7069             2611.836866  Corporate Auto   Two-Door Car   

      monthly premium auto  total claim amount number of open complaints  
0                   1000.0            2.704934                    1/0/00  
1                     94.0         1131.464935                    1/0/00  
2                    108.0          566.472247                    1/0/00  
3                    106.0          529.881344                    1/0/00  
4                     68.0           17.269323                    1/0/00  
...                    ...                 ...                       ...  
7065                  73.0          198.234764                         0  
7066                  79.0          379.200000                         0  
7067                  85.0          790.784983                         3  
7068                  96.0          691.200000                         0  
7069                  77.0          369.600000                         0  

[9135 rows x 10 columns]

### Working with data types – Check the data types of all the columns and fix the incorrect ones 

In [21]:
file4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9135 entries, 0 to 7069
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   gender                     9012 non-null   object 
 1   state                      9134 non-null   object 
 2   education                  9134 non-null   object 
 3   income                     9134 non-null   float64
 4   customer lifetime value    9127 non-null   object 
 5   policy type                9134 non-null   object 
 6   vehicle class              9134 non-null   object 
 7   monthly premium auto       9134 non-null   float64
 8   total claim amount         9134 non-null   float64
 9   number of open complaints  9134 non-null   object 
dtypes: float64(3), object(7)
memory usage: 785.0+ KB


In [22]:
file4.select_dtypes('object')

gender       state             education customer lifetime value  \
0       NaN  Washington                Master                     NaN   
1         F     Arizona              Bachelor              697953.59%   
2         F      Nevada              Bachelor             1288743.17%   
3         M  California              Bachelor              764586.18%   
4         M  Washington  High School or Below              536307.65%   
...     ...         ...                   ...                     ...   
7065      M  California              Bachelor             23405.98798   
7066      F  California               College             3096.511217   
7067      M  California              Bachelor             8163.890428   
7068      M  California               College             7524.442436   
7069      M  California               College             2611.836866   

         policy type  vehicle class number of open complaints  
0      Personal Auto  Four-Door Car                    1/0/00  
1      Personal Auto  Four-Door Car                    1/0/00  
2      Personal Auto   Two-Door Car                    1/0/00  
3     Corporate Auto            SUV                    1/0/00  
4      Personal Auto  Four-Door Car                    1/0/00  
...              ...            ...                       ...  
7065   Personal Auto  Four-Door Car                         0  
7066  Corporate Auto  Four-Door Car                         0  
7067  Corporate Auto  Four-Door Car                         3  
7068   Personal Auto  Four-Door Car                         0  
7069  Corporate Auto   Two-Door Car                         0  

[9135 rows x 7 columns]

In [23]:
file4.nunique()

gender                          5
state                           8
education                       6
income                       5655
customer lifetime value      8211
policy type                     3
vehicle class                   6
monthly premium auto          209
total claim amount           5070
number of open complaints      12
dtype: int64

### Removing the percentage from the customer lifetime value 

In [24]:
file4["customer lifetime value"].unique()

array([nan, '697953.59%', '1288743.17%', ..., 8163.890428, 7524.442436,
       2611.836866], dtype=object)

In [25]:
def delete_unit(file4):
    """deletes % from value"""
    file4["customer lifetime value"] = [i.replace("%","") if isinstance(i, str) else i for i in file4["customer lifetime value"]]
    return file4


In [26]:
delete_unit(file4)

gender       state             education   income  \
0       NaN  Washington                Master      0.0   
1         F     Arizona              Bachelor      0.0   
2         F      Nevada              Bachelor  48767.0   
3         M  California              Bachelor      0.0   
4         M  Washington  High School or Below  36357.0   
...     ...         ...                   ...      ...   
7065      M  California              Bachelor  71941.0   
7066      F  California               College  21604.0   
7067      M  California              Bachelor      0.0   
7068      M  California               College  21941.0   
7069      M  California               College      0.0   

     customer lifetime value     policy type  vehicle class  \
0                        NaN   Personal Auto  Four-Door Car   
1                  697953.59   Personal Auto  Four-Door Car   
2                 1288743.17   Personal Auto   Two-Door Car   
3                  764586.18  Corporate Auto            SUV   
4                  536307.65   Personal Auto  Four-Door Car   
...                      ...             ...            ...   
7065             23405.98798   Personal Auto  Four-Door Car   
7066             3096.511217  Corporate Auto  Four-Door Car   
7067             8163.890428  Corporate Auto  Four-Door Car   
7068             7524.442436   Personal Auto  Four-Door Car   
7069             2611.836866  Corporate Auto   Two-Door Car   

      monthly premium auto  total claim amount number of open complaints  
0                   1000.0            2.704934                    1/0/00  
1                     94.0         1131.464935                    1/0/00  
2                    108.0          566.472247                    1/0/00  
3                    106.0          529.881344                    1/0/00  
4                     68.0           17.269323                    1/0/00  
...                    ...                 ...                       ...  
7065                  73.0          198.234764                         0  
7066                  79.0          379.200000                         0  
7067                  85.0          790.784983                         3  
7068                  96.0          691.200000                         0  
7069                  77.0          369.600000                         0  

[9135 rows x 10 columns]

In [27]:
import numpy as np
import math

In [28]:
# (PZ) normally we put all imports at the very top

### truncating customer lifetime value into an integer value

In [29]:
file4["customer lifetime value"].describe()  

count     9127.00000
unique    8211.00000
top       6057.07208
freq         6.00000
Name: customer lifetime value, dtype: float64

In [30]:
file4["customer lifetime value"] = file4["customer lifetime value"].astype(float)

In [31]:
file4["customer lifetime value"] = file4["customer lifetime value"].apply(lambda x: round(x/1000,0)) # (PZ) changed to 1000

In [32]:
file4["customer lifetime value"].describe()

count    9127.000000
mean      182.078010
std       441.047664
min         2.000000
25%         5.000000
50%         8.000000
75%        26.000000
max      5817.000000
Name: customer lifetime value, dtype: float64

### Cleaning the data for number of open complaints and extracting the middle number

In [33]:
# (PZ) I would try something like 
# list(map(lambda x: int(x[2]) if type(x) == str else x, df["number of open complaints"]))
# to extract the middle element

In [34]:
# or something like

In [35]:
foo = '1/a/00'

In [36]:
foo.strip('1/')[0]

'a'

In [37]:
## (PZ)
temp = list(file4['number of open complaints'].value_counts().index)
temp

[0, '1/0/00', 1, 2, '1/1/00', 3, 4, '1/2/00', '1/3/00', 5, '1/4/00', '1/5/00']

In [38]:
temp

[0, '1/0/00', 1, 2, '1/1/00', 3, 4, '1/2/00', '1/3/00', 5, '1/4/00', '1/5/00']

In [39]:
f = lambda y : list(map(lambda x: int(x.strip('1/')[0]) if type(x) == str else x, y))

In [40]:
f(temp)

[0, 0, 1, 2, 0, 3, 4, 2, 3, 5, 4, 5]

In [41]:
g = lambda p : np.cos(p)

In [42]:
def g(p):
    return np.cos(p)

In [ ]:
f(file4['number of open complaints']) 

In [43]:
file4["number of open complaints"] = file4["number of open complaints"].astype(str)

In [44]:
file4["number of open complaints"].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', 'nan',
       '0', '2', '3', '1', '5', '4'], dtype=object)

In [45]:
# it's not good to call a column this way because u might change the name later and get confused
file4.iloc[:,9][file4["number of open complaints"].str.contains(pat = "1/")] = "0"

/var/folders/lj/my6r3k650wl54v5nz5r6x5cm0000gn/T/ipykernel_41054/1678827028.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file4.iloc[:,9][file4["number of open complaints"].str.contains(pat = "1/")] = "0"


In [46]:
file4

gender       state             education   income  \
0       NaN  Washington                Master      0.0   
1         F     Arizona              Bachelor      0.0   
2         F      Nevada              Bachelor  48767.0   
3         M  California              Bachelor      0.0   
4         M  Washington  High School or Below  36357.0   
...     ...         ...                   ...      ...   
7065      M  California              Bachelor  71941.0   
7066      F  California               College  21604.0   
7067      M  California              Bachelor      0.0   
7068      M  California               College  21941.0   
7069      M  California               College      0.0   

      customer lifetime value     policy type  vehicle class  \
0                         NaN   Personal Auto  Four-Door Car   
1                       698.0   Personal Auto  Four-Door Car   
2                      1289.0   Personal Auto   Two-Door Car   
3                       765.0  Corporate Auto            SUV   
4                       536.0   Personal Auto  Four-Door Car   
...                       ...             ...            ...   
7065                     23.0   Personal Auto  Four-Door Car   
7066                      3.0  Corporate Auto  Four-Door Car   
7067                      8.0  Corporate Auto  Four-Door Car   
7068                      8.0   Personal Auto  Four-Door Car   
7069                      3.0  Corporate Auto   Two-Door Car   

      monthly premium auto  total claim amount number of open complaints  
0                   1000.0            2.704934                         0  
1                     94.0         1131.464935                         0  
2                    108.0          566.472247                         0  
3                    106.0          529.881344                         0  
4                     68.0           17.269323                         0  
...                    ...                 ...                       ...  
7065                  73.0          198.234764                         0  
7066                  79.0          379.200000                         0  
7067                  85.0          790.784983                         3  
7068                  96.0          691.200000                         0  
7069                  77.0          369.600000                         0  

[9135 rows x 10 columns]

In [47]:
file4["number of open complaints"] = file4["number of open complaints"].replace("/00","")

In [48]:
file4["number of open complaints"].unique()

array(['0', 'nan', '2', '3', '1', '5', '4'], dtype=object)

### Standardizing the texts in gender

In [49]:
file4["gender"].unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [50]:
def clean_gender(i):
    if i in ["M", "Male"]:
        return "M"
    elif i in ["F", "female", "Femal"]:
        return "F"
    else:
        return i

In [51]:
file4["gender"] = list(map(clean_gender, file4["gender"])) 

In [52]:
file4["gender"].unique()

array([nan, 'F', 'M'], dtype=object)

In [53]:
file4

gender       state             education   income  \
0       NaN  Washington                Master      0.0   
1         F     Arizona              Bachelor      0.0   
2         F      Nevada              Bachelor  48767.0   
3         M  California              Bachelor      0.0   
4         M  Washington  High School or Below  36357.0   
...     ...         ...                   ...      ...   
7065      M  California              Bachelor  71941.0   
7066      F  California               College  21604.0   
7067      M  California              Bachelor      0.0   
7068      M  California               College  21941.0   
7069      M  California               College      0.0   

      customer lifetime value     policy type  vehicle class  \
0                         NaN   Personal Auto  Four-Door Car   
1                       698.0   Personal Auto  Four-Door Car   
2                      1289.0   Personal Auto   Two-Door Car   
3                       765.0  Corporate Auto            SUV   
4                       536.0   Personal Auto  Four-Door Car   
...                       ...             ...            ...   
7065                     23.0   Personal Auto  Four-Door Car   
7066                      3.0  Corporate Auto  Four-Door Car   
7067                      8.0  Corporate Auto  Four-Door Car   
7068                      8.0   Personal Auto  Four-Door Car   
7069                      3.0  Corporate Auto   Two-Door Car   

      monthly premium auto  total claim amount number of open complaints  
0                   1000.0            2.704934                         0  
1                     94.0         1131.464935                         0  
2                    108.0          566.472247                         0  
3                    106.0          529.881344                         0  
4                     68.0           17.269323                         0  
...                    ...                 ...                       ...  
7065                  73.0          198.234764                         0  
7066                  79.0          379.200000                         0  
7067                  85.0          790.784983                         3  
7068                  96.0          691.200000                         0  
7069                  77.0          369.600000                         0  

[9135 rows x 10 columns]

### Standardizing the texts in state

In [54]:
# PZ using the pandas method replace is also an option here. You can use a dictionary of replacement rules like {"from": "to"}
# 

In [55]:
file4["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [56]:
def clean_state(i):
    if i in ["Washington", "WA"]:
        return "Washington"
    elif i in ["Arizona", "AZ"]:
        return "Arizona"
    else:
        return i

In [57]:
file4["state"] = list(map(clean_state, file4["state"])) 

In [58]:
file4["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       nan], dtype=object)

# Activity 2

Replacing null values – Replace missing values with means of the column (for numerical columns). Pay attention that the Income feature for instance has 0s which is equivalent to null values. (We assume here that there is no such income with 0 as it refers to missing values) Hint: numpy.nan is considered of float64 data type.

In [59]:
file4

gender       state             education   income  \
0       NaN  Washington                Master      0.0   
1         F     Arizona              Bachelor      0.0   
2         F      Nevada              Bachelor  48767.0   
3         M  California              Bachelor      0.0   
4         M  Washington  High School or Below  36357.0   
...     ...         ...                   ...      ...   
7065      M  California              Bachelor  71941.0   
7066      F  California               College  21604.0   
7067      M  California              Bachelor      0.0   
7068      M  California               College  21941.0   
7069      M  California               College      0.0   

      customer lifetime value     policy type  vehicle class  \
0                         NaN   Personal Auto  Four-Door Car   
1                       698.0   Personal Auto  Four-Door Car   
2                      1289.0   Personal Auto   Two-Door Car   
3                       765.0  Corporate Auto            SUV   
4                       536.0   Personal Auto  Four-Door Car   
...                       ...             ...            ...   
7065                     23.0   Personal Auto  Four-Door Car   
7066                      3.0  Corporate Auto  Four-Door Car   
7067                      8.0  Corporate Auto  Four-Door Car   
7068                      8.0   Personal Auto  Four-Door Car   
7069                      3.0  Corporate Auto   Two-Door Car   

      monthly premium auto  total claim amount number of open complaints  
0                   1000.0            2.704934                         0  
1                     94.0         1131.464935                         0  
2                    108.0          566.472247                         0  
3                    106.0          529.881344                         0  
4                     68.0           17.269323                         0  
...                    ...                 ...                       ...  
7065                  73.0          198.234764                         0  
7066                  79.0          379.200000                         0  
7067                  85.0          790.784983                         3  
7068                  96.0          691.200000                         0  
7069                  77.0          369.600000                         0  

[9135 rows x 10 columns]

### Replacing missing values for income

In [60]:
# 0 is considered missing value
file4["income"].unique()

array([    0., 48767., 36357., ..., 66367., 71941., 21941.])

In [61]:
mean_income = file4["income"].mean()
mean_income

37824.84705495949

In [62]:
def zero_to_mean_income(i): 
    """changes value of zero to the mean income of the dataset"""
    mean_income = file4["income"].mean()
    if i == 0:
        return mean_income
    else:
        return i    


In [63]:
# a more direct way is
file4.income.replace(0, file4.income.mean(),inplace=True)
file4.income.min()>0

True

In [64]:
#file4["income"] = list(map(zero_to_mean_income,file4["income"]))

In [65]:
file4.income.min()

10037.0

In [66]:
# still 1 NaN value left
file4["income"].isna().value_counts()

False    9134
True        1
Name: income, dtype: int64

In [67]:
file4.iloc[1071]

gender                       NaN
state                        NaN
education                    NaN
income                       NaN
customer lifetime value      NaN
policy type                  NaN
vehicle class                NaN
monthly premium auto         NaN
total claim amount           NaN
number of open complaints    nan
Name: 1071, dtype: object

In [68]:
filt=file4.income.isna()==True
file4[filt]

gender state education  income  customer lifetime value policy type  \
1071    NaN   NaN       NaN     NaN                      NaN         NaN   

     vehicle class  monthly premium auto  total claim amount  \
1071           NaN                   NaN                 NaN   

     number of open complaints  
1071                       nan

In [69]:
file4["income"] = file4["income"].fillna(mean_income)

In [70]:
file4["income"].isna().value_counts()

False    9135
Name: income, dtype: int64

In [71]:
file4[filt]

gender state education        income  customer lifetime value  \
1071    NaN   NaN       NaN  37824.847055                      NaN   

     policy type vehicle class  monthly premium auto  total claim amount  \
1071         NaN           NaN                   NaN                 NaN   

     number of open complaints  
1071                       nan

In [72]:
# (PZ) the rest of the row is still bad. better to just drop the row
file4.drop(file4[filt].index,axis=0,inplace=True)

### Now replacing missing values for customer lifetime value

In [73]:
file4["customer lifetime value"].unique() # it's not very informative to call unique for a continuous variable

array([  nan,  698., 1289., ...,   68.,   65.,   46.])

In [99]:
# to check for a nan it's better to 
file4['customer lifetime value'].isna().any()

False

In [75]:
#compute mean
mean_clv = file4["customer lifetime value"].mean()
mean_clv

182.09730440499672

In [76]:
#maybe fill up with median instead?
median_clv = file4["customer lifetime value"].median()
median_clv

8.0

In [77]:
file4["customer lifetime value"] = file4["customer lifetime value"].fillna(mean_clv)

In [78]:
#check
file4["customer lifetime value"].unique()

array([ 182.0973044,  698.       , 1289.       , ...,   68.       ,
         65.       ,   46.       ])

### No missing values for monthly premium auto

In [79]:
file4["monthly premium auto"].unique()

array([ 1000.,    94.,   108.,   106.,    68.,    69.,    67.,   101.,
          71.,    93.,   110.,    70.,    64.,    72.,    74.,    79.,
          73.,    61.,   111.,    80.,    63.,   237.,    65.,   130.,
          62.,   117.,    91.,    90.,    66.,    99.,   103., 35354.,
         172.,    92.,   104.,   113.,   124.,   105.,   100.,   112.,
          97.,    95.,   102.,    96.,   186.,    77.,    76.,   119.,
          87.,   109.,   107.,    88.,    85.,  6464.,   133.,    86.,
          78.,    89.,   192.,   118.,   140.,   127.,   126.,    82.,
         115.,   217.,   114.,   138.,    81.,   255.,   150.,   123.,
         116.,   190.,    98.,   159.,    84.,    83.,   152.,   136.,
         245.,   135.,  1005.,   225.,   132.,   153.,   121.,   139.,
         154.,   161.,   156.,   171.,   244.,   183.,   176.,   230.,
         129.,   177.,   181.,   196.,   131.,   276.,   253.,   137.,
         180.,   203.,   147.,   165.,   198.,   125.,   193.,   128.,
      

### No missing values for total claim amount

In [80]:
file4["monthly premium auto"].unique()

array([ 1000.,    94.,   108.,   106.,    68.,    69.,    67.,   101.,
          71.,    93.,   110.,    70.,    64.,    72.,    74.,    79.,
          73.,    61.,   111.,    80.,    63.,   237.,    65.,   130.,
          62.,   117.,    91.,    90.,    66.,    99.,   103., 35354.,
         172.,    92.,   104.,   113.,   124.,   105.,   100.,   112.,
          97.,    95.,   102.,    96.,   186.,    77.,    76.,   119.,
          87.,   109.,   107.,    88.,    85.,  6464.,   133.,    86.,
          78.,    89.,   192.,   118.,   140.,   127.,   126.,    82.,
         115.,   217.,   114.,   138.,    81.,   255.,   150.,   123.,
         116.,   190.,    98.,   159.,    84.,    83.,   152.,   136.,
         245.,   135.,  1005.,   225.,   132.,   153.,   121.,   139.,
         154.,   161.,   156.,   171.,   244.,   183.,   176.,   230.,
         129.,   177.,   181.,   196.,   131.,   276.,   253.,   137.,
         180.,   203.,   147.,   165.,   198.,   125.,   193.,   128.,
      

### Finally replacing missing values for number of open complaints

In [100]:
file4["number of open complaints"].unique()

array([0, 2, 3, 1, 5, 4])

In [108]:
np.median([0,0,0,0,0,0,0, 0, 2, 3, 1, 5, 4])

0.0

In [102]:
file4["number of open complaints"] = file4["number of open complaints"].astype(int)

In [103]:
    file4["number of open complaints"].isna().any()

False

In [104]:
file4['number of open complaints'].value_counts()

0    7693
1     765
2     282
3     230
4     119
5      44
Name: number of open complaints, dtype: int64

In [105]:
mean_noc = file4["number of open complaints"].mean()
mean_noc

0.29727362312493155

In [106]:
 file4["number of open complaints"].median()

0.0

In [107]:
file4["number of open complaints"] = file4["number of open complaints"].astype(int)
median_noc = file4["number of open complaints"].median()
median_noc

0.0

In [89]:
file4["number of open complaints"].fillna()

0       0
1       0
2       0
3       0
4       0
       ..
7065    0
7066    0
7067    3
7068    0
7069    0
Name: number of open complaints, Length: 9133, dtype: int64

In [91]:
file4['number of open complaints']

0       0
1       0
2       0
3       0
4       0
       ..
7065    0
7066    0
7067    3
7068    0
7069    0
Name: number of open complaints, Length: 9133, dtype: int64

In [92]:
file4["number of open complaints"] = file4["number of open complaints"].fillna(value=3)
#check
file4["number of open complaints"].unique()

array([0, 2, 3, 1, 5, 4])

## Write function to turn states into regions

Bucketing the data - Write a function to replace column "State" to different zones. California as West Region, Oregon as North West, and Washington as East, and Arizona and Nevada as Central

In [93]:
def state_into_regions(i):
    if i == "California":
        return "West Region"
    elif i == "Oregon":
        return "North West"
    elif i == "Washington":
        return "East"
    elif i == "Arizona" or i == "Nevada":
        return "Central"
    else:
        return i

In [94]:
file4["state"] = list(map(state_into_regions,file4["state"]))

In [95]:
file4["state"].unique()

array(['East', 'Central', 'West Region', 'North West', 'Cali'],
      dtype=object)

In [96]:
file4

gender        state             education        income  \
0       NaN         East                Master  37824.847055   
1         F      Central              Bachelor  37824.847055   
2         F      Central              Bachelor  48767.000000   
3         M  West Region              Bachelor  37824.847055   
4         M         East  High School or Below  36357.000000   
...     ...          ...                   ...           ...   
7065      M  West Region              Bachelor  71941.000000   
7066      F  West Region               College  21604.000000   
7067      M  West Region              Bachelor  37824.847055   
7068      M  West Region               College  21941.000000   
7069      M  West Region               College  37824.847055   

      customer lifetime value     policy type  vehicle class  \
0                  182.097304   Personal Auto  Four-Door Car   
1                  698.000000   Personal Auto  Four-Door Car   
2                 1289.000000   Personal Auto   Two-Door Car   
3                  765.000000  Corporate Auto            SUV   
4                  536.000000   Personal Auto  Four-Door Car   
...                       ...             ...            ...   
7065                23.000000   Personal Auto  Four-Door Car   
7066                 3.000000  Corporate Auto  Four-Door Car   
7067                 8.000000  Corporate Auto  Four-Door Car   
7068                 8.000000   Personal Auto  Four-Door Car   
7069                 3.000000  Corporate Auto   Two-Door Car   

      monthly premium auto  total claim amount  number of open complaints  
0                   1000.0            2.704934                          0  
1                     94.0         1131.464935                          0  
2                    108.0          566.472247                          0  
3                    106.0          529.881344                          0  
4                     68.0           17.269323                          0  
...                    ...                 ...                        ...  
7065                  73.0          198.234764                          0  
7066                  79.0          379.200000                          0  
7067                  85.0          790.784983                          3  
7068                  96.0          691.200000                          0  
7069                  77.0          369.600000                          0  

[9133 rows x 10 columns]

In [97]:
fil4.to_csv(''

SyntaxError: EOL while scanning string literal (1386972559.py, line 1)