In [ ]:
# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

In [ ]:
#### 1. Import the numpy package under the name `np` (★☆☆)
#hint: import … as`

In [2]:
import numpy as np

In [3]:
#### 2. Create a null vector of size 10 (★☆☆)
#hint: np.zeros`

SyntaxError: invalid syntax (2208439625.py, line 2)

In [4]:
a = np.zeros([10])
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#hint: array[4]`
a = np.array([int(x==4) for x in range(10)])
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [6]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#hint: arange`
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#hint: reshape`
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
print(np.reshape.__doc__)


    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        changing fastest, and the last index changing slowest. Note that
        the 'C

In [16]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#hint: np.nonzero`

a = np.array([1,2,0,0,4,0]) #nonzero returns indices of non-zero elements
indices = np.nonzero(a)
indices

(array([0, 1, 4], dtype=int64),)

In [18]:
#### 7. Create a 3x3 identity matrix = Einheitsmatrix!
#hint: np.eye`
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#hint: np.random.random`
a = np.random.random((3,3,3)) #1:anzahl block 2: höhe block 3: spalten
a

array([[[0.43749497, 0.49281501, 0.60168967],
        [0.67018251, 0.0351337 , 0.96990113],
        [0.70482431, 0.32696432, 0.88150329]],

       [[0.21124144, 0.69868592, 0.52855062],
        [0.47954746, 0.72649608, 0.66963581],
        [0.8640896 , 0.25697626, 0.63596735]],

       [[0.4462032 , 0.29282878, 0.56683055],
        [0.1167652 , 0.10681199, 0.94224282],
        [0.44452251, 0.03090028, 0.86121373]]])

In [45]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#hint: min, max`
a = np.random.random((10,10))
a_min = a.min()
a_min


0.011424626541908456

In [46]:
a_max = a.max()
a_max

0.989487736624734

In [50]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#hint: mean`
a = np.random.random(30)
a_mean = a.mean()
a_mean
a

array([0.34227825, 0.42450812, 0.28592976, 0.55051174, 0.90372733,
       0.32324625, 0.0949113 , 0.03445929, 0.03187842, 0.2229898 ,
       0.20376987, 0.7729441 , 0.63443788, 0.10402145, 0.09638423,
       0.17916099, 0.08956725, 0.25111753, 0.30157768, 0.0235273 ,
       0.70622956, 0.69437743, 0.69447951, 0.65152416, 0.88312023,
       0.64828781, 0.04823871, 0.21500367, 0.97239102, 0.89850903])

In [51]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#hint: np.diag`
a = np.diag(1+np.arange(4), k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [7]:
a = np.diag(1+np.arange(4), k = 1)
a

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [56]:
#### 12. Normalize a 5x5 random matrix #normalizing means here using stdev
#hint: (x -mean)/std`     #random always creates values between 0 and 1
a = np.random.random((5,5))
a_norm = (a-a.mean())/a.std()
a_norm

#new matrix a_norm has than mean of 0 and stdev of 1

array([[ 0.28051899, -1.03533286, -0.41547736,  0.15257611, -1.6860839 ],
       [ 1.5017592 ,  0.77378565, -0.49244505,  0.7525149 , -0.93498028],
       [-0.24442081, -1.59790612,  0.89046564,  0.57082214, -1.4105546 ],
       [ 1.46223321,  1.35153458, -0.31568359,  0.38922158, -0.14239098],
       [ 0.51117526, -1.62269028,  1.34134068, -0.93974957,  0.85976747]])

In [57]:
#### 13. How to find common values between two arrays? (★☆☆)
#hint: np.intersect1d`

a = np.arange(0,9)
b = np.arange(4,9)
a_b = np.intersect1d(a,b)
a_b

array([4, 5, 6, 7, 8])

In [68]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#hint: sort`

In [72]:
a = np.random.random((10)) #sort() is a in-place method, value doesnt need to be stored in new variable
a.sort()
a

array([0.11530613, 0.16544548, 0.19277329, 0.23132244, 0.24216728,
       0.45481358, 0.5123135 , 0.56220528, 0.63949155, 0.69241219])

In [13]:
a = np.sort(np.random.randint(-10,10,(1,10)))
print(a)
print(type(a))
print(a[0])
print(type(a))

[[-8 -8 -1  1  1  4  4  5  7  9]]
<class 'numpy.ndarray'>
[-8 -8 -1  1  1  4  4  5  7  9]
<class 'numpy.ndarray'>


In [74]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#hint: argmax`
a = np.random.random((10)) # arg max (argumentum maximi, dt. Argument des Maximums
a[a.argmax()] = 0
a

array([0.68243091, 0.63392025, 0.34563379, 0.56050061, 0.        ,
       0.23542891, 0.05478709, 0.1074605 , 0.6153512 , 0.69629003])

In [85]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#hint: mean(axis=,keepdims=)`

a = np.arange(0,9).reshape(3,3)
a
#axis along which we want the sum to be computed
#If the axis is None, it will sum all the elements of the input array
#If the axis is negative, the sum is computed from the last to the first axis 
#An axis with a value of 0 will compute the sum along the column
#an axis with a value of 1 will compute row.
#keepdims: true value ensures that the reduced axes are left as dimensions with size one in the output. This ensures that the output is broadcasted correctly against the input array. If a non-default value is passed, keepdims will be passed through to the sum() method of sub-classes of ndarray. In the case of the default value, this will not be done.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
sub_mean = a.mean(axis=0, keepdims=True) #bei axis = 0 bildet mittelwert COLLUMS, y-Achse
sub_mean

array([[3., 4., 5.]])

In [89]:
sub_mean = a.mean(axis=1, keepdims=True) #bei axis = 1 bildet mittelwert ROWS, x-Achse
sub_mean

array([[1.],
       [4.],
       [7.]])

In [107]:
#### 17. How to get the n largest values of an array 
#Z = np.arange(10000)
#np.random.shuffle(Z)
#n = 5
#hint: np.argsort | np.argpartition`
a = np.arange(10000)
print(a)
np.random.shuffle(a)
print(a)

[   0    1    2 ... 9997 9998 9999]
[5927  976 7347 ... 1966 5260 5037]


In [116]:
a = np.arange(10000)
print(a)
random_a = np.random.shuffle(a)
print(random_a)

[   0    1    2 ... 9997 9998 9999]
None


In [14]:
print(np.argsort.__doc__)


    Returns the indices that would sort an array.

    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.

    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.

        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    order : str or list of str, optional
        When `a` is an array with 

In [108]:
print(np.random.shuffle.__doc__)


        shuffle(x)

        Modify a sequence in-place by shuffling its contents.

        This function only shuffles the array along the first axis of a
        multi-dimensional array. The order of sub-arrays is changed but
        their contents remains the same.

        .. note::
            New code should use the ``shuffle`` method of a ``default_rng()``
            instance instead; please see the :ref:`random-quick-start`.

        Parameters
        ----------
        x : ndarray or MutableSequence
            The array, list or mutable sequence to be shuffled.

        Returns
        -------
        None

        See Also
        --------
        Generator.shuffle: which should be used for new code.

        Examples
        --------
        >>> arr = np.arange(10)
        >>> np.random.shuffle(arr)
        >>> arr
        [1 7 5 2 9 4 3 6 0 8] # random

        Multi-dimensional arrays are only shuffled along the first axis:

        >>> arr = np.arange(9).reshape((3, 3)

In [110]:
a_random =  np.random.shuffle(np.arange(10000))

 

In [113]:
a_random =  np.arange(19)

In [114]:
np.random.shuffle(a_random)

In [115]:
a_random

array([16,  9, 15, 14,  3, 12,  8,  6, 13,  5,  7,  0,  1,  2,  4, 11, 10,
       18, 17])

In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#hint: np.where`

In [16]:
rmat35 = np.random.randint(0,10,size=(5,3))
print(rmat35)
rmat35= np.where(rmat35 > 4, rmat35 **2, rmat35)
print(rmat35)

[[4 6 5]
 [0 0 7]
 [8 7 2]
 [7 7 9]
 [2 1 7]]
[[ 4 36 25]
 [ 0  0 49]
 [64 49  2]
 [49 49 81]
 [ 2  1 49]]
